// MockAPI URL - replace with your mockapi.io endpoint
export const MOCKAPI_URL = 'https://67c8abb8c19eb8753e7a6d5a.mockapi.io/api/v1/handbags';

export const BRANDS = ['All', 'Bvlgari', 'Michael Kors', 'Burberry', 'Ferragamo', 'Fendi'];

// Local fallback data
export const LOCAL_HANDBAGS = [
  {
    id: '1',
    handbagName: 'Galuchat Serpenti Forever Crossbody in Red',
    cost: 2798,
    category: 'Crossbody',
    color: ['Red'],
    gender: true,
    uri: 'https://cdn2.jomashop.com/media/catalog/product/cache/fc2ff48f80400416c47c36b80c0a3202/b/v/bvlgari-galuchat-serpenti-forever-crossbody-in-red287977_4.jpg',
    brand: 'Bvlgari',
    percentOff: 0.42,
  },
  {
    id: '2',
    handbagName: 'Ladies Monogram Print Shoulder Bag',
    category: 'Shoulder Bag',
    cost: 215.98,
    color: ['Vanilla', 'Acorn', 'Gray'],
    gender: true,
    uri: 'https://cdn2.jomashop.com/media/catalog/product/cache/fc2ff48f80400416c47c36b80c0a3202/m/i/michael-kors-ladies-monogram-print-shoulder-bag30h1ggrl8v149_6.jpg',
    percentOff: 0.55,
    brand: 'Michael Kors',
  },
  {
    id: '3',
    handbagName: 'Open Box - Logo Print Large Soft Belt Tote',
    color: ['Silver', 'Gray'],
    cost: 583.19,
    category: 'Shoulder Bag',
    gender: true,
    uri: 'https://cdn2.jomashop.com/media/catalog/product/cache/fc2ff48f80400416c47c36b80c0a3202/b/u/burberry-mini-shield-shoulder-bag-8082580_3.jpg',
    brand: 'Burberry',
    percentOff: 0.56,
  },
  {
    id: '4',
    handbagName: 'Logo Embroided Shoulder Bag',
    color: ['Red'],
    cost: 595.0,
    category: 'Shoulder Bag',
    gender: false,
    uri: 'https://cdn2.jomashop.com/media/catalog/product/cache/fc2ff48f80400416c47c36b80c0a3202/f/e/ferragamo-logo-embroided-shoulder-bag-241469-769602_3.jpg',
    brand: 'Ferragamo',
    percentOff: 0.41,
  },
  {
    id: '5',
    handbagName: 'Cut Out-Detail Shoulder Bag',
    color: ['Black', 'Gray'],
    cost: 588.0,
    category: 'Shoulder Bag',
    gender: true,
    uri: 'https://cdn2.jomashop.com/media/catalog/product/cache/fc2ff48f80400416c47c36b80c0a3202/f/e/ferragamo-cut-outdetail-shoulder-bag-213942-762299_2.jpg',
    brand: 'Ferragamo',
    percentOff: 0.4,
  },
  {
    id: '6',
    handbagName: 'Peekaboo Iseeu Mini Leather Bag',
    color: ['Acciaio', 'Palladio', 'Gray'],
    cost: 768.0,
    category: 'Shoulder Bag',
    gender: false,
    uri: 'https://cdn2.jomashop.com/media/catalog/product/cache/fc2ff48f80400416c47c36b80c0a3202/f/e/fendi-peekaboo-iseeu-mini-leather-bag7va530ark0f0fdy_2.jpg',
    brand: 'Fendi',
    percentOff: 0.37,
  },
  {
    id: '7',
    handbagName: 'Olympia Leather Leather Crossbody Card Case',
    color: ['Light Sesame'],
    cost: 278.0,
    category: 'Card Case',
    gender: true,
    uri: 'https://cdn2.jomashop.com/media/catalog/product/cache/fc2ff48f80400416c47c36b80c0a3202/b/u/burberry-olympia-leather-leather-crossbody-card-case8040739_3.jpg',
    brand: 'Burberry',
    percentOff: 0.47,
  },
  {
    id: '8',
    handbagName: 'Black Folded Business Card Holder',
    color: ['Black'],
    cost: 229.0,
    category: 'Card Holder',
    gender: true,
    uri: 'https://cdn2.jomashop.com/media/catalog/product/cache/fc2ff48f80400416c47c36b80c0a3202/b/v/bvlgari-black-folded-business-card-holder-293552_2.jpg',
    brand: 'Bvlgari',
    percentOff: 0.38,
  },
  {
    id: '9',
    handbagName: 'Small Empire Leather Wallet',
    color: ['Beige'],
    cost: 49.89,
    category: 'Card Case',
    gender: true,
    uri: 'https://cdn2.jomashop.com/media/catalog/product/cache/fc2ff48f80400416c47c36b80c0a3202/m/i/michael-kors-small-empire-leather-wallet32s3g8ed0l222_2.jpg',
    brand: 'Michael Kors',
    percentOff: 0.62,
  },
  {
    id: '10',
    handbagName: 'Moments Sterling Silver Open Bangle, Size Small',
    color: ['Brown', 'Acorn'],
    cost: 80.98,
    category: 'Wallets',
    gender: true,
    uri: 'https://cdn2.jomashop.com/media/catalog/product/cache/fc2ff48f80400416c47c36b80c0a3202/m/i/michael-kors-ladies-signature-logo-carmen-medium-envelopetrifold-wallet-brownacorn-32s1gnme6b-252.jpg',
    brand: 'Michael Kors',
    percentOff: 0.55,
  },
  {
    id: '11',
    handbagName: 'Peekaboo Leather Card Case Pouch',
    color: ['Edamame'],
    cost: 298.99,
    category: 'Card Case',
    gender: true,
    uri: 'https://cdn2.jomashop.com/media/catalog/product/cache/fc2ff48f80400416c47c36b80c0a3202/f/e/fendi-peekaboo-leather-card-case-pouch-8ap161a91bf1l1c.jpg',
    brand: 'Fendi',
    percentOff: 0.35,
  },
  {
    id: '12',
    handbagName: 'Logo Series Small Leather Tote',
    color: ['White'],
    cost: 1560.0,
    category: 'Tote Bags',
    gender: true,
    uri: 'https://cdn2.jomashop.com/media/catalog/product/cache/fc2ff48f80400416c47c36b80c0a3202/b/v/bvlgari-logo-series-small-leather-tote-291959_3.jpg',
    brand: 'Bvlgari',
    percentOff: 0.4,
  },
  {
    id: '13',
    handbagName: 'First Sight Flap Shoulder Bag',
    color: ['Blue', 'Light Blue'],
    cost: 1748.98,
    category: 'Shoulder Bag',
    gender: true,
    uri: 'https://cdn2.jomashop.com/media/catalog/product/cache/fc2ff48f80400416c47c36b80c0a3202/f/e/fendi-first-sight-flap-shoulder-bag-8bs072anx2f1l1k_3.jpg',
    brand: 'Fendi',
    percentOff: 0.37,
  },
  {
    id: '14',
    handbagName: 'Serpenti Forever Compact Leather Wallet',
    color: ['Light Blue', 'Cyan'],
    cost: 444.99,
    category: 'Wallets',
    gender: true,
    uri: 'https://cdn2.jomashop.com/media/catalog/product/cache/fc2ff48f80400416c47c36b80c0a3202/a/m/Burberry-amethyst-tassel-bolo-bracelet-in-rose-plated-sterling-silver-jms003978.jpg',
    brand: 'Bvlgari',
    percentOff: 0.4,
  },
];

// Mock feedback data per handbag id
export const MOCK_FEEDBACKS = {
  '1': [
    { id: 'f1', user: 'Alice', rating: 5, comment: 'Absolutely stunning bag! The red color is vibrant and rich.', date: '2024-01-15' },
    { id: 'f2', user: 'Bob', rating: 4, comment: 'Beautiful craftsmanship. A bit pricey but worth it.', date: '2024-02-10' },
    { id: 'f3', user: 'Carol', rating: 5, comment: 'Luxury at its finest. Bvlgari never disappoints.', date: '2024-03-01' },
  ],
  '2': [
    { id: 'f4', user: 'Diana', rating: 4, comment: 'Love the monogram print. Very stylish!', date: '2024-01-20' },
    { id: 'f5', user: 'Eve', rating: 3, comment: 'Good quality but the strap is a bit short.', date: '2024-02-05' },
    { id: 'f6', user: 'Frank', rating: 5, comment: 'Best shoulder bag I have owned!', date: '2024-03-12' },
  ],
  '3': [
    { id: 'f7', user: 'Grace', rating: 4, comment: 'Elegant and spacious. Great for everyday use.', date: '2024-01-25' },
    { id: 'f8', user: 'Henry', rating: 5, comment: 'Burberry quality speaks for itself. Amazing bag.', date: '2024-02-18' },
  ],
  '4': [
    { id: 'f9', user: 'Isabella', rating: 5, comment: 'The red color is so bold and eye-catching!', date: '2024-01-30' },
    { id: 'f10', user: 'Jack', rating: 4, comment: 'Great quality leather. Worth every penny.', date: '2024-03-05' },
    { id: 'f11', user: 'Karen', rating: 3, comment: 'Nice bag but expected more from Ferragamo.', date: '2024-03-20' },
  ],
  '5': [
    { id: 'f12', user: 'Liam', rating: 4, comment: 'The cut-out detail is unique and stylish.', date: '2024-02-01' },
    { id: 'f13', user: 'Mia', rating: 5, comment: 'Love it! Fits my laptop and essentials perfectly.', date: '2024-02-25' },
  ],
  '6': [
    { id: 'f14', user: 'Noah', rating: 5, comment: 'Iconic Fendi bag. Always a showstopper.', date: '2024-01-10' },
    { id: 'f15', user: 'Olivia', rating: 4, comment: 'Elegant and compact. Perfect for evenings.', date: '2024-02-14' },
    { id: 'f16', user: 'Peter', rating: 5, comment: 'Flawless stitching and premium leather.', date: '2024-03-08' },
  ],
  '7': [
    { id: 'f17', user: 'Quinn', rating: 4, comment: 'Practical and stylish card case.', date: '2024-01-18' },
    { id: 'f18', user: 'Rachel', rating: 3, comment: 'Good but small for my needs.', date: '2024-02-22' },
  ],
  '8': [
    { id: 'f19', user: 'Sam', rating: 5, comment: 'Sleek and professional look. Love it!', date: '2024-01-12' },
    { id: 'f20', user: 'Tina', rating: 4, comment: 'Great quality. Fits all my cards perfectly.', date: '2024-03-15' },
  ],
  '9': [
    { id: 'f21', user: 'Uma', rating: 4, comment: 'Compact and well-designed wallet.', date: '2024-02-08' },
    { id: 'f22', user: 'Victor', rating: 5, comment: 'Excellent value for the price!', date: '2024-03-10' },
    { id: 'f23', user: 'Wendy', rating: 3, comment: 'Decent quality but expected more.', date: '2024-03-25' },
  ],
  '10': [
    { id: 'f24', user: 'Xander', rating: 4, comment: 'Beautiful wallet. The brown color is rich.', date: '2024-01-22' },
    { id: 'f25', user: 'Yasmine', rating: 5, comment: 'Gorgeous wallet! Great gift idea.', date: '2024-02-28' },
  ],
  '11': [
    { id: 'f26', user: 'Zoe', rating: 5, comment: 'Adorable Fendi pouch! Very chic.', date: '2024-01-08' },
    { id: 'f27', user: 'Aaron', rating: 4, comment: 'Great for minimalists. Fits essentials only.', date: '2024-02-12' },
  ],
  '12': [
    { id: 'f28', user: 'Betty', rating: 5, comment: 'Classic white tote. Timeless and chic!', date: '2024-01-05' },
    { id: 'f29', user: 'Charlie', rating: 4, comment: 'Beautiful bag but requires careful maintenance.', date: '2024-02-20' },
    { id: 'f30', user: 'Dora', rating: 5, comment: 'Worth every dollar. Stunning piece!', date: '2024-03-18' },
  ],
  '13': [
    { id: 'f31', user: 'Eric', rating: 5, comment: 'The blue color is breathtaking. Love this bag!', date: '2024-01-28' },
    { id: 'f32', user: 'Fiona', rating: 4, comment: 'Beautiful design. Very well-made.', date: '2024-02-16' },
  ],
  '14': [
    { id: 'f33', user: 'George', rating: 4, comment: 'Elegant compact wallet. Light blue is lovely.', date: '2024-01-14' },
    { id: 'f34', user: 'Helen', rating: 5, comment: 'Perfect size and beautiful color!', date: '2024-03-02' },
    { id: 'f35', user: 'Ivan', rating: 3, comment: 'Nice but a bit small.', date: '2024-03-22' },
  ],
};
